return to the original version

diff --git a/maynard.in b/maynard.in
--- a/maynard.in
+++ b/maynard.in
@@ -1,21 +1,44 @@
 #! /bin/sh
-#	©2014-2016 YUICHIRO NAKADA
 
-#export WAYLAND_DISPLAY="wayland-0"
-export GDK_BACKEND=wayland CLUTTER_BACKEND=wayland
-export GTK_IM_MODULE="bim"
-export QT_IM_MODULE="bim"
+PREFIX=@prefix@
+LIBEXECDIR=$PREFIX/libexec
+ABS_BUILDDIR=@abs_builddir@
+DEFAULT_BACKGROUND=/usr/share/wallpapers/Hanami/contents/images/3872x2592.jpg
 
-PREFIX=/usr
+md5() {
+    cat "$1" 2> /dev/null | md5sum
+}
 
-[ -n "$1" ] && opt="-u $1"
+check_install() {
+    local_maynard="$ABS_BUILDDIR/shell/maynard"
+    installed_maynard="$LIBEXECDIR/maynard"
+    if [ ! -e "$local_maynard" -o \
+         ! -e "$installed_maynard" -o \
+         "`md5 \"$local_maynard\"`" != "`md5 \"$installed_maynard\"`" ]; then
+        echo "It looks like you forgot to run 'make install'." >&2
+        exit 1
+    fi
+}
+
+mkdir ~/.config > /dev/null 2>&1
+
+if [ -z "${MAYNARD_BACKGROUND+_}" -a \
+     -e "$DEFAULT_BACKGROUND" ]; then
+    export MAYNARD_BACKGROUND="$DEFAULT_BACKGROUND"
+fi
 
 xdpyinfo > /dev/null 2>&1
 if [ "$?" = "0" ]; then
-	# We are running under X, so let's assume this is a development installation.
-	XDG_DATA_DIRS=$XDG_DATA_DIRS:$PREFIX/share/ $PREFIX/bin/weston
+    # We are running under X, so let's assume this is a development
+    # installation.
+    if ! cat /etc/os-release 2> /dev/null | grep 'ID=raspbian' > /dev/null; then
+        # Non-Raspbian, we can launch weston under X.
+        check_install
+        XDG_DATA_DIRS=$XDG_DATA_DIRS:$PREFIX/share/ $PREFIX/bin/weston
+    else
+        echo "You cannot run Maynard under X." >&2
+        exit 1
+    fi
 else
-	#weston-launch ${opt} || weston-launch ${opt} -- --backend=fbdev-backend.so --use-gl
-	exec weston
+    weston-launch
 fi
-
